name: Maven Build

on:
  push:
    branches: [ release* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: snapshots
        server-username: ${{secrets.JFROG_USER}}
        server-password: ${{secrets.JFROG_PASS}}
    - name: Build with Maven
      run: mvn clean install
