name: Maven Build

on:
  push:
    branches: [ release* ]

jobs:
  build:
    env:
      JFROG_USER: ${{secrets.JFROG_USER}}
      JFROG_PASS: ${{secrets.JFROG_PASS}}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: mvn clean install
